DROP DATABASE IF EXISTS `wecodi`;
CREATE DATABASE `wecodi`
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON wecodi.* TO 'master'@'localhost' IDENTIFIED BY '1234'

WITH GRANT OPTION;
FLUSH PRIVILEGES;
