# Generated by Django 2.2.4 on 2019-08-31 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ArticleCategory',
            },
        ),
        migrations.CreateModel(
            name='Styletag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylename', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Styletag',
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('thumb_img', models.TextField()),
                ('articleCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleCategory')),
                ('styletag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.Styletag')),
            ],
            options={
                'db_table': 'Article',
            },
        ),
    ]
