# Generated by Django 2.2.4 on 2019-09-04 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ArticleCategory',
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('thumb_img', models.URLField(max_length=2500)),
                ('articleCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.ArticleCategory')),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Styletag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Styletag',
            },
        ),
        migrations.CreateModel(
            name='HeartCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('articlemodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleModel')),
                ('usermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel')),
            ],
            options={
                'db_table': 'Heart',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='styletag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.Styletag'),
        ),
    ]
