# Generated by Django 2.2.4 on 2019-09-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecategory',
            old_name='categoryname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='styletag',
            old_name='stylename',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='thumb_img',
            field=models.URLField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
