# Generated by Django 2.2.4 on 2019-09-08 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articlemodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleModel')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
    ]
